#pragma once

typedef enum {
    GFS_DISPLAY_PICTURE,
    GFS_PLAY_FMV,
    GFS_PLAY_LEVEL,
    GFS_PLAY_CUTSCENE,
    GFS_LEVEL_COMPLETE,
    GFS_GAME_COMPLETE,
    GFS_SET_MUSIC_TRACK,
    GFS_SET_CAMERA_ANGLE,
    GFS_SET_START_ANIM,
    GFS_SET_NUM_SECRETS,
    GFS_DISABLE_FLOOR,
    GFS_ENABLE_SUNSET,
    GFS_ADD_ITEM,
    GFS_ADD_SECRET_REWARD,
    GFS_REMOVE_WEAPONS,
    GFS_REMOVE_AMMO,
} GAME_FLOW_SEQUENCE_EVENT_TYPE;
