#pragma once

typedef enum {
#if TR_VERSION == 2
    GFL_NO_LEVEL = -1,
#endif
    GFL_TITLE = 0,
    GFL_NORMAL = 1,
    GFL_SAVED = 2,
    GFL_DEMO = 3,
    GFL_CUTSCENE = 4,
#if TR_VERSION == 1
    GFL_GYM = 5,
    GFL_CURRENT = 6,
    GFL_RESTART = 7,
    GFL_SELECT = 8,
    GFL_BONUS = 9,
    GFL_TITLE_DEMO_PC = 10,
    GFL_LEVEL_DEMO_PC = 11,
#elif TR_VERSION == 2
    GFL_STORY = 5,
    GFL_QUIET = 6,
    GFL_MID_STORY = 7,
#endif
} GAME_FLOW_LEVEL_TYPE;

typedef enum {
    GF_NOOP = -1,
    GF_START_GAME,
    GF_START_CINE,
    GF_START_FMV,
    GF_START_DEMO,
    GF_EXIT_TO_TITLE,
    GF_LEVEL_COMPLETE,
    GF_EXIT_GAME,
    GF_START_SAVED_GAME,
#if TR_VERSION == 1
    GF_RESTART_GAME,
#endif
    GF_SELECT_GAME,
#if TR_VERSION == 1
    GF_START_GYM,
    GF_STORY_SO_FAR,
#endif
} GAME_FLOW_ACTION;

typedef enum {
    GFS_DISPLAY_PICTURE,
    GFS_PLAY_LEVEL,
    GFS_PLAY_FMV,
#if TR_VERSION == 1
    GFS_LEVEL_STATS,
    GFS_TOTAL_STATS,
    GFS_LOADING_SCREEN,
    GFS_LOAD_LEVEL,
    GFS_EXIT_TO_TITLE,
    GFS_EXIT_TO_LEVEL,
    GFS_EXIT_TO_CINE,
#elif TR_VERSION == 2
    GFS_PLAY_CUTSCENE,
    GFS_LEVEL_COMPLETE,
    GFS_GAME_COMPLETE,
#endif
    GFS_SET_CAMERA_ANGLE,
    GFS_ADD_ITEM,
    GFS_REMOVE_WEAPONS,
    GFS_REMOVE_AMMO,
#if TR_VERSION == 1
    GFS_REMOVE_MEDIPACKS,
    GFS_REMOVE_SCIONS,
    GFS_PLAY_SYNCED_AUDIO,
    GFS_FLIP_MAP,
    GFS_MESH_SWAP,
    GFS_SETUP_BACON_LARA,
#elif TR_VERSION == 2
    GFS_SET_START_ANIM,
    GFS_SET_NUM_SECRETS,
    GFS_DISABLE_FLOOR,
    GFS_ENABLE_SUNSET,
    GFS_ADD_SECRET_REWARD,
#endif
} GAME_FLOW_SEQUENCE_EVENT_TYPE;
