// This file is autogenerated. To update it, run tools/generate_funcs.

#pragma once

#include "global/types.h"

// clang-format off
#define Output_InsertInventoryBackground ((void __cdecl (*)(const int16_t *obj_ptr))0x00401D50)
#define DingDong_Control ((void __cdecl (*)(int16_t item_num))0x0041D210)
#define LaraAlarm_Control ((void __cdecl (*)(int16_t item_num))0x0041D250)
#define AlarmSound_Control ((void __cdecl (*)(int16_t item_num))0x0041D290)
#define BirdTweeter_Control ((void __cdecl (*)(int16_t item_num))0x0041D300)
#define DoChimeSound ((void __cdecl (*)(ITEM *item))0x0041D360)
#define ClockChimes_Control ((void __cdecl (*)(int16_t item_num))0x0041D3C0)
#define SphereOfDoom_Collision ((void __cdecl (*)(int16_t item_num, ITEM *lara_item, COLL_INFO *coll))0x0041D430)
#define SphereOfDoom_Control ((void __cdecl (*)(int16_t item_num))0x0041D560)
#define SphereOfDoom_Draw ((void __cdecl (*)(const ITEM *item))0x0041D650)
#define FX_LaraDrawRightGun ((void __cdecl (*)(ITEM *item))0x0041D7A0)
#define FX_LaraDrawLeftGun ((void __cdecl (*)(ITEM *item))0x0041D7F0)
#define FX_SwapMeshesWithMeshSwap1 ((void __cdecl (*)(ITEM *item))0x0041D840)
#define FX_SwapMeshesWithMeshSwap2 ((void __cdecl (*)(ITEM *item))0x0041D8B0)
#define FX_SwapMeshesWithMeshSwap3 ((void __cdecl (*)(ITEM *item))0x0041D920)
#define FX_InvisibilityOn ((void __cdecl (*)(ITEM *item))0x0041D9C0)
#define FX_InvisibilityOff ((void __cdecl (*)(ITEM *item))0x0041D9D0)
#define FX_DynamicLightOn ((void __cdecl (*)(ITEM *item))0x0041D9F0)
#define FX_DynamicLightOff ((void __cdecl (*)(ITEM *item))0x0041DA00)
#define FX_ResetHair ((void __cdecl (*)(ITEM *item))0x0041DA10)
#define FX_AssaultStop ((void __cdecl (*)(ITEM *item))0x0041DA50)
#define FX_AssaultReset ((void __cdecl (*)(ITEM *item))0x0041DA70)
#define FX_AssaultFinished ((void __cdecl (*)(ITEM *item))0x0041DA90)
#define Earthquake_Control ((void __cdecl (*)(int16_t item_num))0x00434210)
#define FinalCutscene_Control ((void __cdecl (*)(int16_t item_num))0x004342F0)
#define InitialiseFinalLevel ((void __cdecl (*)(void))0x00434330)
#define MiniCopterControl ((void __cdecl (*)(int16_t item_num))0x00434610)
#define BigBowl_Control ((void __cdecl (*)(int16_t item_num))0x00434C10)
#define CopterControl ((void __cdecl (*)(int16_t item_num))0x00435B80)
#define GeneralControl ((void __cdecl (*)(int16_t item_num))0x00435C90)
#define Glow_Control ((void __cdecl (*)(int16_t fx_num))0x00435E90)
#define GunFlash_Control ((void __cdecl (*)(int16_t fx_num))0x00435ED0)
#define Secret_Control ((void __cdecl (*)(int16_t item_num))0x00438EC0)
// clang-format on
