// This file is autogenerated. To update it, run tools/generate_funcs.

#pragma once

#include "global/types.h"

// clang-format off
#define Output_InsertInventoryBackground ((void __cdecl (*)(const int16_t *obj_ptr))0x00401D50)
#define SphereOfDoom_Draw ((void __cdecl (*)(const ITEM *item))0x0041D650)
#define Earthquake_Control ((void __cdecl (*)(int16_t item_num))0x00434210)
#define FinalCutscene_Control ((void __cdecl (*)(int16_t item_num))0x004342F0)
#define InitialiseFinalLevel ((void __cdecl (*)(void))0x00434330)
#define MiniCopterControl ((void __cdecl (*)(int16_t item_num))0x00434610)
#define BigBowl_Control ((void __cdecl (*)(int16_t item_num))0x00434C10)
#define CopterControl ((void __cdecl (*)(int16_t item_num))0x00435B80)
#define GeneralControl ((void __cdecl (*)(int16_t item_num))0x00435C90)
#define Glow_Control ((void __cdecl (*)(int16_t fx_num))0x00435E90)
#define GunFlash_Control ((void __cdecl (*)(int16_t fx_num))0x00435ED0)
#define Secret_Control ((void __cdecl (*)(int16_t item_num))0x00438EC0)
// clang-format on
