#include "game/inventory_ring/vars.h"

#include "global/vars.h"

int32_t g_Inv_OptionObjectsCount = 4;
int16_t g_Inv_MainObjectsCount = 8;
int16_t g_Inv_Chosen = -1;
INVENTORY_MODE g_Inv_Mode = INV_TITLE_MODE;
uint16_t g_Inv_MainCurrent;
uint16_t g_Inv_KeyObjectsCount;
uint16_t g_Inv_KeysCurrent;
uint16_t g_Inv_OptionCurrent;
TEXTSTRING *g_InvRing_Text = NULL;
bool g_Inv_DemoMode;
bool g_Inv_IsOptionsDelay;
int32_t g_Inv_OptionsDelayCounter;
int32_t g_Inv_ExtraData[8];
int32_t g_Inv_NFrames = 2;
TEXTSTRING *g_Inv_ItemText[IT_NUMBER_OF] = {};

INV_ITEM *g_Inv_OptionList[] = {
    // clang-format off
    &g_Inv_Item_Passport,
    &g_Inv_Item_Controls,
    &g_Inv_Item_Sound,
    &g_Inv_Item_Photo,
    // clang-format on
};

INV_ITEM *g_Inv_MainList[23] = {
    // clang-format off
    &g_Inv_Item_Stopwatch,
    &g_Inv_Item_Flare,
    &g_Inv_Item_Pistols,
    &g_Inv_Item_Shotgun,
    &g_Inv_Item_Magnums,
    &g_Inv_Item_Uzis,
    &g_Inv_Item_M16,
    &g_Inv_Item_Grenade,
    &g_Inv_Item_Harpoon,
    &g_Inv_Item_LargeMedi,
    &g_Inv_Item_SmallMedi,
    NULL,
    // clang-format on
};

INV_ITEM *g_Inv_KeysList[23] = {
    // clang-format off
    &g_Inv_Item_Puzzle1,
    &g_Inv_Item_Puzzle2,
    &g_Inv_Item_Puzzle3,
    &g_Inv_Item_Puzzle4,
    &g_Inv_Item_Key1,
    &g_Inv_Item_Key2,
    &g_Inv_Item_Key3,
    &g_Inv_Item_Key4,
    &g_Inv_Item_Pickup1,
    &g_Inv_Item_Pickup2,
    NULL,
    // clang-format on
};

INV_ITEM g_Inv_Item_Stopwatch = {
    .string = NULL,
    .object_id = O_COMPASS_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4352,
    .x_rot_pt = 0,
    .x_rot_sel = 64000,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 4294967126,
    .y_trans = 0,
    .z_trans_sel = 320,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 0,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Pistols = {
    .string = NULL,
    .object_id = O_PISTOL_OPTION,
    .frames_total = 12,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 11,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 2848,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 32768,
    .y_rot = 0,
    .y_trans_sel = 38,
    .y_trans = 0,
    .z_trans_sel = 352,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 1,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Flare = {
    .string = NULL,
    .object_id = O_FLARES_OPTION,
    .frames_total = 31,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 30,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 0,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 57344,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 8,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Shotgun = {
    .string = NULL,
    .object_id = O_SHOTGUN_OPTION,
    .frames_total = 13,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 12,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 5120,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 30720,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 228,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 2,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Magnums = {
    .string = NULL,
    .object_id = O_MAGNUM_OPTION,
    .frames_total = 12,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 11,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 3360,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 32768,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 362,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 3,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Uzis = {
    .string = NULL,
    .object_id = O_UZI_OPTION,
    .frames_total = 13,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 12,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 2336,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 32768,
    .y_rot = 0,
    .y_trans_sel = 56,
    .y_trans = 0,
    .z_trans_sel = 322,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 4,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Harpoon = {
    .string = NULL,
    .object_id = O_HARPOON_OPTION,
    .frames_total = 12,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 11,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 64800,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 46080,
    .y_rot = 0,
    .y_trans_sel = 58,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 7,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_M16 = {
    .string = NULL,
    .object_id = O_M16_OPTION,
    .frames_total = 12,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 11,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 65312,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 47104,
    .y_rot = 0,
    .y_trans_sel = 84,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 5,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Grenade = {
    .string = NULL,
    .object_id = O_GRENADE_OPTION,
    .frames_total = 12,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 11,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 65312,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 14336,
    .y_rot = 0,
    .y_trans_sel = 56,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 6,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_PistolAmmo = {
    .string = NULL,
    .object_id = O_PISTOL_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 1,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_ShotgunAmmo = {
    .string = NULL,
    .object_id = O_SHOTGUN_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 2,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_MagnumAmmo = {
    .string = NULL,
    .object_id = O_MAGNUM_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 3,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_UziAmmo = {
    .string = NULL,
    .object_id = O_UZI_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 4,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_HarpoonAmmo = {
    .string = NULL,
    .object_id = O_HARPOON_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 7,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_M16Ammo = {
    .string = NULL,
    .object_id = O_M16_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 5,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_GrenadeAmmo = {
    .string = NULL,
    .object_id = O_GRENADE_AMMO_OPTION,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3200,
    .x_rot_pt = 0,
    .x_rot_sel = 61728,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 296,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 6,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_SmallMedi = {
    .string = NULL,
    .object_id = O_SMALL_MEDIPACK_OPTION,
    .frames_total = 26,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 25,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4032,
    .x_rot_pt = 0,
    .x_rot_sel = 58240,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 61440,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 216,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 11,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_LargeMedi = {
    .string = NULL,
    .object_id = O_LARGE_MEDIPACK_OPTION,
    .frames_total = 20,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 19,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 3616,
    .x_rot_pt = 0,
    .x_rot_sel = 57376,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 61440,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 352,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 10,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Pickup1 = {
    .string = NULL,
    .object_id = O_PICKUP_OPTION_1,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 111,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Pickup2 = {
    .string = NULL,
    .object_id = O_PICKUP_OPTION_2,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 110,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Puzzle1 = {
    .string = NULL,
    .object_id = O_PUZZLE_OPTION_1,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 108,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Puzzle2 = {
    .string = NULL,
    .object_id = O_PUZZLE_OPTION_2,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 107,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Puzzle3 = {
    .string = NULL,
    .object_id = O_PUZZLE_OPTION_3,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 106,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Puzzle4 = {
    .string = NULL,
    .object_id = O_PUZZLE_OPTION_4,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 105,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Key1 = {
    .string = NULL,
    .object_id = O_KEY_OPTION_1,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 101,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Key2 = {
    .string = NULL,
    .object_id = O_KEY_OPTION_2,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 102,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Key3 = {
    .string = NULL,
    .object_id = O_KEY_OPTION_3,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 103,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Key4 = {
    .string = NULL,
    .object_id = 200,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 7200,
    .x_rot_pt = 0,
    .x_rot_sel = 61184,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 256,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 104,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Passport = {
    .string = NULL,
    .object_id = 133,
    .frames_total = 30,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 14,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4640,
    .x_rot_pt = 0,
    .x_rot_sel = 61216,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 384,
    .z_trans = 0,
    .meshes_sel = 19,
    .meshes_drawn = 19,
    .inv_pos = 0,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Graphics = {
    .string = NULL,
    .object_id = 153,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4224,
    .x_rot_pt = 0,
    .x_rot_sel = 58304,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 16,
    .y_trans = 0,
    .z_trans_sel = 444,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 1,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Sound = {
    .string = NULL,
    .object_id = 154,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4832,
    .x_rot_pt = 0,
    .x_rot_sel = 60128,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 62464,
    .y_rot = 0,
    .y_trans_sel = 4294967294,
    .y_trans = 0,
    .z_trans_sel = 350,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 2,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Controls = {
    .string = NULL,
    .object_id = 155,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 5504,
    .x_rot_pt = 0,
    .x_rot_sel = 62976,
    .x_rot_nosel = 5632,
    .x_rot = 5632,
    .y_rot_sel = 13312,
    .y_rot = 0,
    .y_trans_sel = 46,
    .y_trans = 0,
    .z_trans_sel = 508,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 3,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};

INV_ITEM g_Inv_Item_Photo = {
    .string = NULL,
    .object_id = 122,
    .frames_total = 1,
    .current_frame = 0,
    .goal_frame = 0,
    .open_frame = 0,
    .anim_direction = 1,
    .anim_speed = 1,
    .anim_count = 0,
    .x_rot_pt_sel = 4640,
    .x_rot_pt = 0,
    .x_rot_sel = 61216,
    .x_rot_nosel = 0,
    .x_rot = 0,
    .y_rot_sel = 0,
    .y_rot = 0,
    .y_trans_sel = 0,
    .y_trans = 0,
    .z_trans_sel = 384,
    .z_trans = 0,
    .meshes_sel = -1,
    .meshes_drawn = -1,
    .inv_pos = 5,
    .sprite_list = NULL,
    .reserved = { 0, 0, 0, 0 },
};
